it('User Flow Test', () => {
  cy.visit('http://localhost:3000/')
  cy.url().should('include', '/search?sortBy=vote_average&genre=all')
  cy.get('input')
    .should('be.empty')
  cy.get('input')
    .type('gemini')
  cy.contains('SEARCH').click()
  cy.url().should('include', '/search/gemini?sortBy=vote_average&genre=all')
  cy.get('input')
    .should('have.value', 'gemini')
  cy.contains('Edit')
    .should('have.length', 1);
  cy.contains('Gemini').click()
  cy.get('input')
    .should('not.exist')
  cy.get('SEARCH')
    .should('not.exist')
})
